SELECT COUNT(*)
FROM "MEMBER"
WHERE MEMBER_NICKNAME = ' '
AND MEMBER_DEL_FL = 'N';


-- 이메일이 일치하는 회원 정보 조회
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_ADDRESS, 
 MEMBER_DEL_FL, 
 TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일"') ENROLL_DATE
FROM "MEMBER" 
WHERE MEMBER_EMAIL = 'user01@kh.or.kr'
AND ROWNUM = 1;	


-- 회원 목록 조회
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_DEL_FL
FROM "MEMBER"
ORDER BY MEMBER_NO;

SELECT * FROM MEMBER;

