SELECT COUNT(*)
FROM "MEMBER"
WHERE MEMBER_NICKNAME = ' '
AND MEMBER_DEL_FL = 'N';


-- 이메일이 일치하는 회원 정보 조회
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_ADDRESS, 
 MEMBER_DEL_FL, 
 TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일"') ENROLL_DATE
FROM "MEMBER" 
WHERE MEMBER_EMAIL = 'user01@kh.or.kr'
AND ROWNUM = 1;	


-- 회원 목록 조회
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_DEL_FL
FROM "MEMBER"
ORDER BY MEMBER_NO;

SELECT * FROM MEMBER;

SELECT * FROM BOARD_TYPE

-- "COMMENT" 테이	블 PARENT_NO 컬럼 NULL 허용
ALTER TABLE "COMMENT"
MODIFY PARENT_NO NULL;

-- BOARD 테이블 샘플 데이터 삽입(PL/SQL)
BEGIN
	FOR I IN 1..2000 LOOP
		INSERT INTO BOARD
		VALUES(SEQ_BOARD_NO.NEXTVAL, 
			   SEQ_BOARD_NO.CURRVAL || '번째 게시글',
			   SEQ_BOARD_NO.CURRVAL || '번째 게시글입니다.<br>안녕하세요',
			   DEFAULT, DEFAULT, DEFAULT, DEFAULT, 6, 
			   CEIL(DBMS_RANDOM.VALUE(0,4)));
	END LOOP;
END;
/

COMMIT;

-- COMMENT 테이블 샘플 데이터 삽입(PL/SQL)
BEGIN
   FOR I IN 1..2000 LOOP
      INSERT INTO "COMMENT" 
      VALUES(SEQ_COMMENT_NO.NEXTVAL, 
            SEQ_COMMENT_NO.CURRVAL || '번째 댓글',
            DEFAULT, DEFAULT,
             CEIL(DBMS_RANDOM.VALUE(0,2000)),
             1, NULL);
   END LOOP;
END;
/

-- BOARD_IMG 테이블 샘플데이터 삽입
SELECT * FROM BOARD_IMG;

SELECT COUNT(*) FROM "BOARD" WHERE BOARD_CODE = 1;
SELECT * FROM "BOARD"
WHERE BOARD_CODE =1
ORDER BY 1 DESC;
--1991, 1984, 1980, 1979

INSERT INTO BOARD_IMG 
VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/', '20221116105843_00001.gif', '1.gif', 0, 1991);

INSERT INTO BOARD_IMG 
VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/', '20221116105843_00002.gif', '2.gif', 0, 1984);

INSERT INTO BOARD_IMG 
VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/', '20221116105843_00003.gif', '3.gif', 0, 1980);

INSERT INTO BOARD_IMG 
VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/', '20221116105843_00004.gif', '4.gif', 0, 1979);

COMMIT;

--BOARD_LIKE 테이블 샘플데이터 삽입
SELECT * FROM BOARD_LIKE;



INSERT INTO BOARD_LIKE VALUES(1991, 6);
INSERT INTO BOARD_LIKE VALUES(1984, 6);

COMMIT;


-- 특정 게시판 목록 조회
-- 게시글 번호, 제목, 작성자닉네임, 조회수, 작성일 + 댓글 수, 좋아요 수, 썸네일

SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT, 
	CASE  
      WHEN SYSDATE - B_CREATE_DATE < 1/24/60
      THEN FLOOR( (SYSDATE - B_CREATE_DATE) * 24 * 60 * 60 ) || '초 전'
      WHEN SYSDATE - B_CREATE_DATE < 1/24
      THEN FLOOR( (SYSDATE - B_CREATE_DATE) * 24 * 60) || '분 전'
      WHEN SYSDATE - B_CREATE_DATE < 1
      THEN FLOOR( (SYSDATE - B_CREATE_DATE) * 24) || '시간 전'
      ELSE TO_CHAR(B_CREATE_DATE, 'YYYY-MM-DD')
   END B_CREATE_DATE,
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT,
	(SELECT COUNT(*) FROM BOARD_LIKE L
	WHERE L.BOARD_NO = B.BOARD_NO) LIKE_COUNT,
	(SELECT IMG_PATH || IMG_RENAME FROM BOARD_IMG I
	WHERE IMG_ORDER = 0
	AND I.BOARD_NO = B.BOARD_NO) THUMBNAIL
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_CODE = 1
AND BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;


-- 댓글 수 
SELECT COUNT(*) FROM "COMMENT"
WHERE BOARD_NO = 1991


-- 좋아요 수 
SELECT COUNT(*) FROM BOARD_LIKE L
WHERE BOARD_NO = 1991;

-- 썸네일 이미지 조회
SELECT IMG_PATH || IMG_RENAME FROM BOARD_IMG I
WHERE IMG_ORDER = 0
AND I.BOARD_NO = 1991;


-- 게시글 수 조회 (삭제 제외)
SELECT COUNT(*) FROM BOARD
WHERE BOARD_CODE = 1
AND BOARD_DEL_FL = 'N';


-- 특정 게시글 상세 조회
SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, 
READ_COUNT, 
TO_CHAR(B_CREATE_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') -- 2022년 11월 18일 10:33:21
B_UPDATE_DATE, 
FROM BOARD
-- 특정 게시글 이미지 모두 조회

-- 특정 게시글 댓글 모두 조회(어려움)

SELECT * FROM BOARD

-- 조회 수 증가
UPDATE BOARD SET
READ_COUNT = READ_COUNT + 1
WHERE BOARD_NO = 1;

-- 게시글 상세조회 (좋아요 수 추가)
SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, 
READ_COUNT, 
	TO_CHAR(B_CREATE_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') B_CREATE_DATE, -- 2022년 11월 18일 10:33:21
	TO_CHAR(B_UPDATE_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') B_UPDATE_DATE, -- 2022년 11월 18일 10:33:21
	MEMBER_NO, MEMBER_NICKNAME, PROFILE_IMG,
	(SELECT COUNT(*) FROM BOARD_LIKE L
	 WHERE L.BOARD_NO = B.BOARD_NO)LIKE_COUNT
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_NO = 1991
AND BOARD_DEL_FL = 'N'



SELECT * FROM BOARD_LIKE;

INSERT INTO BOARD_LIKE VALUES(1991, 1);

DELETE FROM BOARD_LIKE
WHERE BOARD_NO = 1991 
AND MEMBER_NO = 1;

COMMIT;
ROLLBACK;

SELECT * FROM MEMBER


UPDATE MEMBER SET
SECESSION_FL = 'N'
WHERE MEMBER_NO = 9





